spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_system
    username: cowowner
    password: mycow
    driver-class-name: org.postgresql.Driver